### ISSUE TITLE
[Meeting] 대면&비대면 회의 

### ISSUE THREAD

**Issue by minzero31** [isliese/ParkingZoneManagementSystemForDisabled#10]
<1차 회의 >
회의 날짜 : 5/16
회의 안건 : 1. 기말프로젝트 주제 정하기
                  2. 개발 일정 정하기
                  3. 역할 분담하기
                  4. 제안서 개요 작성하기

**Comment by minzero31** [comment]
<2차 회의>
회의 날짜 : 5/20
회의 안건 : 1. 주제 정하기 => 주차관리
                  2. 주제 관련해서 모듈 정하기
                  3. 개발 일정 확정하기
                  4. 역할 분담 확정하기

**Comment by minzero31** [comment]
<3차 회의>
회의 날짜 : 5/24
회의 안건 : 개발 일정 구체화하기

**Comment by yeonujirong** [comment]
<4차 회의>
회의 날짜: 5/26일
회의 안건: 개발 툴에 대한 논의 (앱이냐 웹이냐)
----> 파이썬 flask로 웹 개발로 확정

**Comment by yeonujirong** [comment]
<5차 회의>
회의 날짜: 6월 2일
회의 안건: 역할 분담 확정
1. AI/ML : 김민영, 이연우
- 번호판 인식 알고리즘 github 찾기 및 데이터 구축
- 번호판 인식 코드 돌리기&테스트
2. 프론트엔드 : 김찬란, 이연진
- flask 웹페이지 생성 github 링크 찾아보기: 사용하기 편한것, 개발 환경 구축하기
- UI 그림 그리기 (아이패드 or figma)
- 웹페이지 구축 및 대략적인 UI 컴포넌트들을 화면 별로 구상
3. 백엔드 : 김민영, 이연우
