### ISSUE TITLE
[To-do] 2024.06.19 새벽 개발 진행 상황 공유 및 이연진에게 할 일 할당

### ISSUE THREAD

**Issue by isliese** [isliese/ParkingZoneManagementSystemForDisabled#14]
[새벽 개발 진행 결과 공유]
  새벽에 Figma툴로 NoDisabled 페이지에 버튼 추가했고 신고 화면도 구상한 상태임. 지금까지의 코드에서 약간의 오류 수정 및 디벨롭 포함.
  추가적으로, 화면이 답답하여 CopyRight.png 파일도 변경한 상태임. 그런데 지금 Home 화면만 최적화 해놓은 상태라 나머지 html 파일을 Chrome에서 열어보면 CopyRight.png 파일의 비율 이상할 것임. 나머지 html 파일도 화면 최적화 하면 비율이 맞춰질 것으로 예상됨. 
 
[@Yeonjin0121이 내일 아침 할 일]
  @isliese가 새로운 화면의 기능 설명을 Notion에 작성하고 수정 완료한 코드를 Github Front 브랜치에 push 해놓은 상태임. @Yeonjin0121은 Notion을 참고하여 코드를 다운 받아, NoDisabled.html 파일에 신고 버튼을 추가하고, 신고 화면을 "Report.html" 이름으로 구현해주길 바람. (이 화면 또한 Home Button 누르면 Home.html로 화면 전환 해야함) 혹시 시간이 남는다면 나머지 html 파일도 최적화 시도해보길 바람.

**Comment by slwnoey** [comment]
1 Github Push 이슈로 나머지 html 파일 최적화는 시도하지 못함
2 Notion을 참고하여 Report.html을 구현하고 Home를 누르면 화면 전환 완료함 + 신고 URL 연결 완료
3 NoDisabled.html에 신고 버튼 추가 완료함 + 신고하기 텍스트를 삽입함
4 Disabled.html에도 Home 누르면 화면 전환 되도록 수정 완료함

가지고 있는 코드가 온전하지 못해서 새로 만든 화면 등과의 연결은 추후 시도해야함
