### ISSUE TITLE
[To-Do] Front 6월 19일 해야할 일 ( 추가 )

### ISSUE THREAD

**Issue by slwnoey** [isliese/ParkingZoneManagementSystemForDisabled#15]
- 화면 별 최적화
- Report.html에 텍스트 받아오기 (차량 번호에 따라 상단에 차량 번호)
- 화면간 연결 ( ParkingLot -> Disabled or NoDisabled , NoDisabled -> Report )..
- Back과의 연결
- 그 외 편의 기능 구현 ( Disabled & NoDisabled에 멘트 추가 ex) " 장애인 등록 차량이 아닙니다 " 등등 )
- 특정한 이메일과 비밀번호로만 로그인 할 수 있도록 하기

**Comment by isliese** [comment]
화면 간 연결 완료
Disabled & NoDisabled에 멘트 추가 ex) " 장애인 등록 차량이 아닙니다 " 완료
