### ISSUE TITLE
[To-Do] 백엔드 6월 19일 해야 할 일

### ISSUE THREAD

**Issue by yeonujirong** [isliese/ParkingZoneManagementSystemForDisabled#17]
<img width="959" alt="6월 19일" src="https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/165574399/91235c04-1acf-4938-8897-7fa9b6fc992e">

1. 프론트 웹사이트 연결하기 위해서 app.py실행 완료

2. 프론트와 데이터 주고받기 위해 준비

**Comment by isliese** [comment]
완료
