### ISSUE TITLE
[Error] 프론트와 백 연결 

### ISSUE THREAD

**Issue by isliese** [isliese/ParkingZoneManagementSystemForDisabled#20]
프론트에서, 각 Car 요소들의 isDisabled 변수 값을 app.py로 넘겨서 백과 연결해야 하는데, 이 부분에서 오류 발생. 
주의 요함.

**Comment by slwnoey** [comment]
회의 결과 :

@Yeonjin0121  @isliese @minzero31 @yeonujirong 
> 확인 후 구현 부탁

[ 구현 방법 ]
1. Front에서 차 요소 클릭 시 VirtualCarNumber가 파이썬 파일로 넘어감
2. 가상 번호를 인식 후 해당 차량 이미지 => ActualCarNumber을 텍스트로 변환
3. ActualCarNumber + 장애인 등록 차량 여부 구분 코드를 덧붙임
4. 구분코드와 함께 차량 번호를 다시 Front쪽으로 넘겨줌 ( app.py ?)
- 넘겨주는 과정은 여러가지 시도를 해보아야할듯
5. 넘겨준 번호를 가지고 화면에 ActualCarNumber 표시 및 다음 페이지(장애인 등록 차량이 맞습니다 or 장애인 등록 차량이 아닙니다)로 넘어가도록 구현

!!  백 구현시 Front 브랜치 참고하길바람
