### ISSUE TITLE
[To-do] Front에 각종 기능 구현

### ISSUE THREAD

**Issue by slwnoey** [isliese/ParkingZoneManagementSystemForDisabled#7]
- 5초 뒤 메인 화면 복귀 오류 해결 => 이건 @isliese이 작성한 코드 참고하기  

![스크린샷 2024-06-18 013814](https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/126753671/6b911f55-b67a-4b19-b374-36ebfc131470)

- 로그인 입력 필드 구현 => @Yeonjin0121 버그 수정 완료
- 차 객체 하나당 클릭 및 페이지 구현
- 차 객체별 번호판 받아오는 기능 구현

**Comment by slwnoey** [comment]
- 로그인 및 회원가입 입력 필드 구현 완료

<img width="879" alt="스크린샷 2024-06-18 오전 1 01 45" src="https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/165582326/c06f71b6-d9db-40dd-acd4-e6a61991545a">

**Comment by isliese** [comment]
6월 18일 내일 학교에서 만나서 오류 마저 해결합시다

**Comment by isliese** [comment]
6월 18일 학교에서 만나서 기능 구현 및 오류 해결 완료
