### ISSUE TITLE
[Error] 자동차 번호판 인식 OpenCV 오류 

### ISSUE THREAD

**Issue by minzero31** [isliese/ParkingZoneManagementSystemForDisabled#9]
pytesseract와 opencv를 사용한 번호판 인식 코드를 오픈소스로 받아와서 실행시키는 과정에서 오류 발생
<img width="619" alt="opencv오류" src="https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/80385982/e0ac762a-5d7c-4d2e-9621-971ee876ba75">
<img width="443" alt="오류 발생 이미지 경로" src="https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/80385982/d96f02f6-0adc-47e6-b991-7a322c661b86">
![오류#1 발생 부분](https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/80385982/e8084fc1-4a32-41bd-9047-7df2aa259dad)
![오류#1 발생하지 않는 이미지 경로](https://github.com/isliese/ParkingZoneManagementSystemForDisabled/assets/80385982/1e407a1f-73b7-47f1-a481-74e41c921c15)

**Comment by yeonujirong** [comment]
[오류 해결]
가상 환경 설정으로 인해 이미지 파일을 불러올 수 없어서 오류 발생인해 이미지 파일을 불러올 수 없어서 오류 발생
가상 환경 삭제하고 base에서 실행시킴
계속 경로 오류 발생해서 파이썬 환경 변수 수정
pytesseract 오류 발생해서 다시 다운받고 환경 변수 수정 (C:\\Program Files\\Tesseract-OCR)
오류 해결 완료
